const PROTOCOL_DIVISION_BASE = 1000000
const TOKEN_DECIMALS_MULTIPLIER = 1000000000000000000
const CACHE_UPDATE_INTERVAL = 1000 * 60 * 60 * 2 // Updates every 2 hours
const TOKEN_DECIMAL_UNITS = 18
const VALID_SUBSCRIPTION_FREQUENCIES = ['weekly', 'daily']

module.exports = {
  PROTOCOL_DIVISION_BASE,
  TOKEN_DECIMALS_MULTIPLIER,
  TOKEN_DECIMAL_UNITS,
  CACHE_UPDATE_INTERVAL,
  VALID_SUBSCRIPTION_FREQUENCIES
}
